title: Blog Bang Roy Han
description: Bang roy han alias bangroy adalah panggilan kepada seorang pria bernama Moh. Royhan Nahado yang berprofesi sebagai programmer dan content writer.
show_downloads: false
theme: jekyll-theme-cayman